name: CI
on:
  push:
    branches: ["**"]
  pull_request:
jobs:
  run-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: python -m pip install --upgrade pip
      - run: pip install .
      - run: pip install numpy
      - run: python example/main.py
